ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/"
  user: "postgres"
  password: "postgres"
jwt:
  secret: "secret"
  issuer: "http://localhost:8080/"
  audience: "http://localhost:8080/hello"
  realm: "Access to 'hello'"